function Able(a, fpath) 
{
// =======================================================
var idOpn = charIDToTypeID( "Opn " );
    var desc1 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
    desc1.putPath( idnull, new File( fpath.toString()+a.toString()+"Pik.eps" ) );
    var idAs = charIDToTypeID( "As  " );
        var desc2 = new ActionDescriptor();
        var idRslt = charIDToTypeID( "Rslt" );
        var idRsl = charIDToTypeID( "#Rsl" );
        desc2.putUnitDouble( idRslt, idRsl, 600.000000 );
        var idAntA = charIDToTypeID( "AntA" );
        desc2.putBoolean( idAntA, true );
        var idCnsP = charIDToTypeID( "CnsP" );
        desc2.putBoolean( idCnsP, true );
    var idEPSG = charIDToTypeID( "EPSG" );
    desc1.putObject( idAs, idEPSG, desc2 );
executeAction( idOpn, desc1, DialogModes.NO );

// =======================================================
var idClrR = charIDToTypeID( "ClrR" );
    var desc3 = new ActionDescriptor();
    var idFzns = charIDToTypeID( "Fzns" );
    desc3.putInteger( idFzns, 49 );
    var idMnm = charIDToTypeID( "Mnm " );
        var desc4 = new ActionDescriptor();
        var idLmnc = charIDToTypeID( "Lmnc" );
        desc4.putDouble( idLmnc, 100.000000 );
        var idA = charIDToTypeID( "A   " );
        desc4.putDouble( idA, 0.000000 );
        var idB = charIDToTypeID( "B   " );
        desc4.putDouble( idB, 0.000000 );
    var idLbCl = charIDToTypeID( "LbCl" );
    desc3.putObject( idMnm, idLbCl, desc4 );
    var idMxm = charIDToTypeID( "Mxm " );
        var desc5 = new ActionDescriptor();
        var idLmnc = charIDToTypeID( "Lmnc" );
        desc5.putDouble( idLmnc, 100.000000 );
        var idA = charIDToTypeID( "A   " );
        desc5.putDouble( idA, 0.000000 );
        var idB = charIDToTypeID( "B   " );
        desc5.putDouble( idB, 0.000000 );
    var idLbCl = charIDToTypeID( "LbCl" );
    desc3.putObject( idMxm, idLbCl, desc5 );
    var idcolorModel = stringIDToTypeID( "colorModel" );
    desc3.putInteger( idcolorModel, 0 );
executeAction( idClrR, desc3, DialogModes.NO );

// =======================================================
var idDlt = charIDToTypeID( "Dlt " );
executeAction( idDlt, undefined, DialogModes.NO );

// =======================================================
var idsetd = charIDToTypeID( "setd" );
    var desc6 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref1 = new ActionReference();
        var idChnl = charIDToTypeID( "Chnl" );
        var idfsel = charIDToTypeID( "fsel" );
        ref1.putProperty( idChnl, idfsel );
    desc6.putReference( idnull, ref1 );
    var idT = charIDToTypeID( "T   " );
    var idOrdn = charIDToTypeID( "Ordn" );
    var idNone = charIDToTypeID( "None" );
    desc6.putEnumerated( idT, idOrdn, idNone );
executeAction( idsetd, desc6, DialogModes.NO );

// =======================================================
var idslct = charIDToTypeID( "slct" );
    var desc7 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref2 = new ActionReference();
        var idrectangleTool = stringIDToTypeID( "rectangleTool" );
        ref2.putClass( idrectangleTool );
    desc7.putReference( idnull, ref2 );
    var iddontRecord = stringIDToTypeID( "dontRecord" );
    desc7.putBoolean( iddontRecord, true );
    var idforceNotify = stringIDToTypeID( "forceNotify" );
    desc7.putBoolean( idforceNotify, true );
executeAction( idslct, desc7, DialogModes.NO );

// =======================================================
var idMk = charIDToTypeID( "Mk  " );
    var desc8 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref3 = new ActionReference();
        var idcontentLayer = stringIDToTypeID( "contentLayer" );
        ref3.putClass( idcontentLayer );
    desc8.putReference( idnull, ref3 );
    var idUsng = charIDToTypeID( "Usng" );
        var desc9 = new ActionDescriptor();
        var idType = charIDToTypeID( "Type" );
            var desc10 = new ActionDescriptor();
            var idClr = charIDToTypeID( "Clr " );
                var desc11 = new ActionDescriptor();
                var idRd = charIDToTypeID( "Rd  " );
                desc11.putDouble( idRd, 255.000000 );
                var idGrn = charIDToTypeID( "Grn " );
                desc11.putDouble( idGrn, 255.000000 );
                var idBl = charIDToTypeID( "Bl  " );
                desc11.putDouble( idBl, 255.000000 );
            var idRGBC = charIDToTypeID( "RGBC" );
            desc10.putObject( idClr, idRGBC, desc11 );
        var idsolidColorLayer = stringIDToTypeID( "solidColorLayer" );
        desc9.putObject( idType, idsolidColorLayer, desc10 );
        var idShp = charIDToTypeID( "Shp " );
            var desc12 = new ActionDescriptor();
            var idTop = charIDToTypeID( "Top " );
            var idRlt = charIDToTypeID( "#Rlt" );
            desc12.putUnitDouble( idTop, idRlt, 168.000000 );
            var idLeft = charIDToTypeID( "Left" );
            var idRlt = charIDToTypeID( "#Rlt" );
            desc12.putUnitDouble( idLeft, idRlt, 314.040000 );
            var idBtom = charIDToTypeID( "Btom" );
            var idRlt = charIDToTypeID( "#Rlt" );
            desc12.putUnitDouble( idBtom, idRlt, 338.160000 );
            var idRght = charIDToTypeID( "Rght" );
            var idRlt = charIDToTypeID( "#Rlt" );
            desc12.putUnitDouble( idRght, idRlt, 328.200000 );
        var idRctn = charIDToTypeID( "Rctn" );
        desc9.putObject( idShp, idRctn, desc12 );
        var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
            var desc13 = new ActionDescriptor();
            var idstrokeStyleVersion = stringIDToTypeID( "strokeStyleVersion" );
            desc13.putInteger( idstrokeStyleVersion, 2 );
            var idstrokeEnabled = stringIDToTypeID( "strokeEnabled" );
            desc13.putBoolean( idstrokeEnabled, true );
            var idfillEnabled = stringIDToTypeID( "fillEnabled" );
            desc13.putBoolean( idfillEnabled, true );
            var idstrokeStyleLineWidth = stringIDToTypeID( "strokeStyleLineWidth" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc13.putUnitDouble( idstrokeStyleLineWidth, idPnt, 1.000000 );
            var idstrokeStyleLineDashOffset = stringIDToTypeID( "strokeStyleLineDashOffset" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc13.putUnitDouble( idstrokeStyleLineDashOffset, idPnt, 0.000000 );
            var idstrokeStyleMiterLimit = stringIDToTypeID( "strokeStyleMiterLimit" );
            desc13.putDouble( idstrokeStyleMiterLimit, 100.000000 );
            var idstrokeStyleLineCapType = stringIDToTypeID( "strokeStyleLineCapType" );
            var idstrokeStyleLineCapType = stringIDToTypeID( "strokeStyleLineCapType" );
            var idstrokeStyleButtCap = stringIDToTypeID( "strokeStyleButtCap" );
            desc13.putEnumerated( idstrokeStyleLineCapType, idstrokeStyleLineCapType, idstrokeStyleButtCap );
            var idstrokeStyleLineJoinType = stringIDToTypeID( "strokeStyleLineJoinType" );
            var idstrokeStyleLineJoinType = stringIDToTypeID( "strokeStyleLineJoinType" );
            var idstrokeStyleMiterJoin = stringIDToTypeID( "strokeStyleMiterJoin" );
            desc13.putEnumerated( idstrokeStyleLineJoinType, idstrokeStyleLineJoinType, idstrokeStyleMiterJoin );
            var idstrokeStyleLineAlignment = stringIDToTypeID( "strokeStyleLineAlignment" );
            var idstrokeStyleLineAlignment = stringIDToTypeID( "strokeStyleLineAlignment" );
            var idstrokeStyleAlignInside = stringIDToTypeID( "strokeStyleAlignInside" );
            desc13.putEnumerated( idstrokeStyleLineAlignment, idstrokeStyleLineAlignment, idstrokeStyleAlignInside );
            var idstrokeStyleScaleLock = stringIDToTypeID( "strokeStyleScaleLock" );
            desc13.putBoolean( idstrokeStyleScaleLock, false );
            var idstrokeStyleStrokeAdjust = stringIDToTypeID( "strokeStyleStrokeAdjust" );
            desc13.putBoolean( idstrokeStyleStrokeAdjust, false );
            var idstrokeStyleLineDashSet = stringIDToTypeID( "strokeStyleLineDashSet" );
                var list1 = new ActionList();
            desc13.putList( idstrokeStyleLineDashSet, list1 );
            var idstrokeStyleBlendMode = stringIDToTypeID( "strokeStyleBlendMode" );
            var idBlnM = charIDToTypeID( "BlnM" );
            var idNrml = charIDToTypeID( "Nrml" );
            desc13.putEnumerated( idstrokeStyleBlendMode, idBlnM, idNrml );
            var idstrokeStyleOpacity = stringIDToTypeID( "strokeStyleOpacity" );
            var idPrc = charIDToTypeID( "#Prc" );
            desc13.putUnitDouble( idstrokeStyleOpacity, idPrc, 100.000000 );
            var idstrokeStyleContent = stringIDToTypeID( "strokeStyleContent" );
                var desc14 = new ActionDescriptor();
                var idClr = charIDToTypeID( "Clr " );
                    var desc15 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc15.putDouble( idRd, 9.065307 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc15.putDouble( idGrn, 1.446433 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc15.putDouble( idBl, 3.503439 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc14.putObject( idClr, idRGBC, desc15 );
            var idsolidColorLayer = stringIDToTypeID( "solidColorLayer" );
            desc13.putObject( idstrokeStyleContent, idsolidColorLayer, desc14 );
            var idstrokeStyleResolution = stringIDToTypeID( "strokeStyleResolution" );
            desc13.putDouble( idstrokeStyleResolution, 600.000000 );
        var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
        desc9.putObject( idstrokeStyle, idstrokeStyle, desc13 );
    var idcontentLayer = stringIDToTypeID( "contentLayer" );
    desc8.putObject( idUsng, idcontentLayer, desc9 );
executeAction( idMk, desc8, DialogModes.NO );

// =======================================================
var idslct = charIDToTypeID( "slct" );
    var desc16 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref4 = new ActionReference();
        var idmarqueeRectTool = stringIDToTypeID( "marqueeRectTool" );
        ref4.putClass( idmarqueeRectTool );
    desc16.putReference( idnull, ref4 );
    var iddontRecord = stringIDToTypeID( "dontRecord" );
    desc16.putBoolean( iddontRecord, true );
    var idforceNotify = stringIDToTypeID( "forceNotify" );
    desc16.putBoolean( idforceNotify, true );
executeAction( idslct, desc16, DialogModes.NO );

// =======================================================
var idsetd = charIDToTypeID( "setd" );
    var desc17 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref5 = new ActionReference();
        var idChnl = charIDToTypeID( "Chnl" );
        var idfsel = charIDToTypeID( "fsel" );
        ref5.putProperty( idChnl, idfsel );
    desc17.putReference( idnull, ref5 );
    var idT = charIDToTypeID( "T   " );
        var desc18 = new ActionDescriptor();
        var idTop = charIDToTypeID( "Top " );
        var idRlt = charIDToTypeID( "#Rlt" );
        desc18.putUnitDouble( idTop, idRlt, 168.120000 );
        var idLeft = charIDToTypeID( "Left" );
        var idRlt = charIDToTypeID( "#Rlt" );
        desc18.putUnitDouble( idLeft, idRlt, 314.040000 );
        var idBtom = charIDToTypeID( "Btom" );
        var idRlt = charIDToTypeID( "#Rlt" );
        desc18.putUnitDouble( idBtom, idRlt, 338.280000 );
        var idRght = charIDToTypeID( "Rght" );
        var idRlt = charIDToTypeID( "#Rlt" );
        desc18.putUnitDouble( idRght, idRlt, 328.200000 );
    var idRctn = charIDToTypeID( "Rctn" );
    desc17.putObject( idT, idRctn, desc18 );
executeAction( idsetd, desc17, DialogModes.NO );

// =======================================================
var idClrR = charIDToTypeID( "ClrR" );
    var desc19 = new ActionDescriptor();
    var idFzns = charIDToTypeID( "Fzns" );
    desc19.putInteger( idFzns, 175 );
    var idMnm = charIDToTypeID( "Mnm " );
        var desc20 = new ActionDescriptor();
        var idLmnc = charIDToTypeID( "Lmnc" );
        desc20.putDouble( idLmnc, 75.640000 );
        var idA = charIDToTypeID( "A   " );
        desc20.putDouble( idA, -10.090000 );
        var idB = charIDToTypeID( "B   " );
        desc20.putDouble( idB, -19.040000 );
    var idLbCl = charIDToTypeID( "LbCl" );
    desc19.putObject( idMnm, idLbCl, desc20 );
    var idMxm = charIDToTypeID( "Mxm " );
        var desc21 = new ActionDescriptor();
        var idLmnc = charIDToTypeID( "Lmnc" );
        desc21.putDouble( idLmnc, 75.640000 );
        var idA = charIDToTypeID( "A   " );
        desc21.putDouble( idA, -10.090000 );
        var idB = charIDToTypeID( "B   " );
        desc21.putDouble( idB, -19.040000 );
    var idLbCl = charIDToTypeID( "LbCl" );
    desc19.putObject( idMxm, idLbCl, desc21 );
    var idcolorModel = stringIDToTypeID( "colorModel" );
    desc19.putInteger( idcolorModel, 0 );
executeAction( idClrR, desc19, DialogModes.NO );

// =======================================================
var idDlt = charIDToTypeID( "Dlt " );
executeAction( idDlt, undefined, DialogModes.NO );

// =======================================================
var idslct = charIDToTypeID( "slct" );
    var desc22 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref6 = new ActionReference();
        var idrectangleTool = stringIDToTypeID( "rectangleTool" );
        ref6.putClass( idrectangleTool );
    desc22.putReference( idnull, ref6 );
    var iddontRecord = stringIDToTypeID( "dontRecord" );
    desc22.putBoolean( iddontRecord, true );
    var idforceNotify = stringIDToTypeID( "forceNotify" );
    desc22.putBoolean( idforceNotify, true );
executeAction( idslct, desc22, DialogModes.NO );

// =======================================================
var idMk = charIDToTypeID( "Mk  " );
    var desc23 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref7 = new ActionReference();
        var idcontentLayer = stringIDToTypeID( "contentLayer" );
        ref7.putClass( idcontentLayer );
    desc23.putReference( idnull, ref7 );
    var idUsng = charIDToTypeID( "Usng" );
        var desc24 = new ActionDescriptor();
        var idType = charIDToTypeID( "Type" );
            var desc25 = new ActionDescriptor();
            var idClr = charIDToTypeID( "Clr " );
                var desc26 = new ActionDescriptor();
                var idRd = charIDToTypeID( "Rd  " );
                desc26.putDouble( idRd, 149.001617 );
                var idGrn = charIDToTypeID( "Grn " );
                desc26.putDouble( idGrn, 193.000946 );
                var idBl = charIDToTypeID( "Bl  " );
                desc26.putDouble( idBl, 221.000519 );
            var idRGBC = charIDToTypeID( "RGBC" );
            desc25.putObject( idClr, idRGBC, desc26 );
        var idsolidColorLayer = stringIDToTypeID( "solidColorLayer" );
        desc24.putObject( idType, idsolidColorLayer, desc25 );
        var idShp = charIDToTypeID( "Shp " );
            var desc27 = new ActionDescriptor();
            var idTop = charIDToTypeID( "Top " );
            var idRlt = charIDToTypeID( "#Rlt" );
            desc27.putUnitDouble( idTop, idRlt, 154.080000 );
            var idLeft = charIDToTypeID( "Left" );
            var idRlt = charIDToTypeID( "#Rlt" );
            desc27.putUnitDouble( idLeft, idRlt, 314.280000 );
            var idBtom = charIDToTypeID( "Btom" );
            var idRlt = charIDToTypeID( "#Rlt" );
            desc27.putUnitDouble( idBtom, idRlt, 338.160000 );
            var idRght = charIDToTypeID( "Rght" );
            var idRlt = charIDToTypeID( "#Rlt" );
            desc27.putUnitDouble( idRght, idRlt, 328.200000 );
        var idRctn = charIDToTypeID( "Rctn" );
        desc24.putObject( idShp, idRctn, desc27 );
        var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
            var desc28 = new ActionDescriptor();
            var idstrokeStyleVersion = stringIDToTypeID( "strokeStyleVersion" );
            desc28.putInteger( idstrokeStyleVersion, 2 );
            var idstrokeEnabled = stringIDToTypeID( "strokeEnabled" );
            desc28.putBoolean( idstrokeEnabled, true );
            var idfillEnabled = stringIDToTypeID( "fillEnabled" );
            desc28.putBoolean( idfillEnabled, true );
            var idstrokeStyleLineWidth = stringIDToTypeID( "strokeStyleLineWidth" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc28.putUnitDouble( idstrokeStyleLineWidth, idPnt, 1.000000 );
            var idstrokeStyleLineDashOffset = stringIDToTypeID( "strokeStyleLineDashOffset" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc28.putUnitDouble( idstrokeStyleLineDashOffset, idPnt, 0.000000 );
            var idstrokeStyleMiterLimit = stringIDToTypeID( "strokeStyleMiterLimit" );
            desc28.putDouble( idstrokeStyleMiterLimit, 100.000000 );
            var idstrokeStyleLineCapType = stringIDToTypeID( "strokeStyleLineCapType" );
            var idstrokeStyleLineCapType = stringIDToTypeID( "strokeStyleLineCapType" );
            var idstrokeStyleButtCap = stringIDToTypeID( "strokeStyleButtCap" );
            desc28.putEnumerated( idstrokeStyleLineCapType, idstrokeStyleLineCapType, idstrokeStyleButtCap );
            var idstrokeStyleLineJoinType = stringIDToTypeID( "strokeStyleLineJoinType" );
            var idstrokeStyleLineJoinType = stringIDToTypeID( "strokeStyleLineJoinType" );
            var idstrokeStyleMiterJoin = stringIDToTypeID( "strokeStyleMiterJoin" );
            desc28.putEnumerated( idstrokeStyleLineJoinType, idstrokeStyleLineJoinType, idstrokeStyleMiterJoin );
            var idstrokeStyleLineAlignment = stringIDToTypeID( "strokeStyleLineAlignment" );
            var idstrokeStyleLineAlignment = stringIDToTypeID( "strokeStyleLineAlignment" );
            var idstrokeStyleAlignInside = stringIDToTypeID( "strokeStyleAlignInside" );
            desc28.putEnumerated( idstrokeStyleLineAlignment, idstrokeStyleLineAlignment, idstrokeStyleAlignInside );
            var idstrokeStyleScaleLock = stringIDToTypeID( "strokeStyleScaleLock" );
            desc28.putBoolean( idstrokeStyleScaleLock, false );
            var idstrokeStyleStrokeAdjust = stringIDToTypeID( "strokeStyleStrokeAdjust" );
            desc28.putBoolean( idstrokeStyleStrokeAdjust, false );
            var idstrokeStyleLineDashSet = stringIDToTypeID( "strokeStyleLineDashSet" );
                var list2 = new ActionList();
            desc28.putList( idstrokeStyleLineDashSet, list2 );
            var idstrokeStyleBlendMode = stringIDToTypeID( "strokeStyleBlendMode" );
            var idBlnM = charIDToTypeID( "BlnM" );
            var idNrml = charIDToTypeID( "Nrml" );
            desc28.putEnumerated( idstrokeStyleBlendMode, idBlnM, idNrml );
            var idstrokeStyleOpacity = stringIDToTypeID( "strokeStyleOpacity" );
            var idPrc = charIDToTypeID( "#Prc" );
            desc28.putUnitDouble( idstrokeStyleOpacity, idPrc, 100.000000 );
            var idstrokeStyleContent = stringIDToTypeID( "strokeStyleContent" );
                var desc29 = new ActionDescriptor();
                var idClr = charIDToTypeID( "Clr " );
                    var desc30 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc30.putDouble( idRd, 9.065307 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc30.putDouble( idGrn, 1.446433 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc30.putDouble( idBl, 3.503439 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc29.putObject( idClr, idRGBC, desc30 );
            var idsolidColorLayer = stringIDToTypeID( "solidColorLayer" );
            desc28.putObject( idstrokeStyleContent, idsolidColorLayer, desc29 );
            var idstrokeStyleResolution = stringIDToTypeID( "strokeStyleResolution" );
            desc28.putDouble( idstrokeStyleResolution, 600.000000 );
        var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
        desc24.putObject( idstrokeStyle, idstrokeStyle, desc28 );
    var idcontentLayer = stringIDToTypeID( "contentLayer" );
    desc23.putObject( idUsng, idcontentLayer, desc24 );
executeAction( idMk, desc23, DialogModes.NO );

// =======================================================
var idslct = charIDToTypeID( "slct" );
    var desc31 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref8 = new ActionReference();
        var idmoveTool = stringIDToTypeID( "moveTool" );
        ref8.putClass( idmoveTool );
    desc31.putReference( idnull, ref8 );
    var iddontRecord = stringIDToTypeID( "dontRecord" );
    desc31.putBoolean( iddontRecord, true );
    var idforceNotify = stringIDToTypeID( "forceNotify" );
    desc31.putBoolean( idforceNotify, true );
executeAction( idslct, desc31, DialogModes.NO );

// =======================================================
var idslct = charIDToTypeID( "slct" );
    var desc32 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref9 = new ActionReference();
        var idrectangleTool = stringIDToTypeID( "rectangleTool" );
        ref9.putClass( idrectangleTool );
    desc32.putReference( idnull, ref9 );
    var iddontRecord = stringIDToTypeID( "dontRecord" );
    desc32.putBoolean( iddontRecord, true );
    var idforceNotify = stringIDToTypeID( "forceNotify" );
    desc32.putBoolean( idforceNotify, true );
executeAction( idslct, desc32, DialogModes.NO );

// =======================================================
var idTrnf = charIDToTypeID( "Trnf" );
    var desc33 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref10 = new ActionReference();
        var idPath = charIDToTypeID( "Path" );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref10.putEnumerated( idPath, idOrdn, idTrgt );
    desc33.putReference( idnull, ref10 );
    var idFTcs = charIDToTypeID( "FTcs" );
    var idQCSt = charIDToTypeID( "QCSt" );
    var idQcsa = charIDToTypeID( "Qcsa" );
    desc33.putEnumerated( idFTcs, idQCSt, idQcsa );
    var idOfst = charIDToTypeID( "Ofst" );
        var desc34 = new ActionDescriptor();
        var idHrzn = charIDToTypeID( "Hrzn" );
        var idRlt = charIDToTypeID( "#Rlt" );
        desc34.putUnitDouble( idHrzn, idRlt, 0.000000 );
        var idVrtc = charIDToTypeID( "Vrtc" );
        var idRlt = charIDToTypeID( "#Rlt" );
        desc34.putUnitDouble( idVrtc, idRlt, -6.000000 );
    var idOfst = charIDToTypeID( "Ofst" );
    desc33.putObject( idOfst, idOfst, desc34 );
    var idHght = charIDToTypeID( "Hght" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc33.putUnitDouble( idHght, idPrc, 106.518905 );
executeAction( idTrnf, desc33, DialogModes.NO );

// =======================================================
var idsetd = charIDToTypeID( "setd" );
    var desc35 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref11 = new ActionReference();
        var idcontentLayer = stringIDToTypeID( "contentLayer" );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref11.putEnumerated( idcontentLayer, idOrdn, idTrgt );
    desc35.putReference( idnull, ref11 );
    var idT = charIDToTypeID( "T   " );
        var desc36 = new ActionDescriptor();
        var idFlCn = charIDToTypeID( "FlCn" );
            var desc37 = new ActionDescriptor();
            var idClr = charIDToTypeID( "Clr " );
                var desc38 = new ActionDescriptor();
                var idRd = charIDToTypeID( "Rd  " );
                desc38.putDouble( idRd, 159.686963 );
                var idGrn = charIDToTypeID( "Grn " );
                desc38.putDouble( idGrn, 159.686948 );
                var idBl = charIDToTypeID( "Bl  " );
                desc38.putDouble( idBl, 159.686948 );
            var idRGBC = charIDToTypeID( "RGBC" );
            desc37.putObject( idClr, idRGBC, desc38 );
        var idsolidColorLayer = stringIDToTypeID( "solidColorLayer" );
        desc36.putObject( idFlCn, idsolidColorLayer, desc37 );
        var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
            var desc39 = new ActionDescriptor();
            var idstrokeStyleVersion = stringIDToTypeID( "strokeStyleVersion" );
            desc39.putInteger( idstrokeStyleVersion, 2 );
            var idfillEnabled = stringIDToTypeID( "fillEnabled" );
            desc39.putBoolean( idfillEnabled, true );
        var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
        desc36.putObject( idstrokeStyle, idstrokeStyle, desc39 );
    var idshapeStyle = stringIDToTypeID( "shapeStyle" );
    desc35.putObject( idT, idshapeStyle, desc36 );
executeAction( idsetd, desc35, DialogModes.NO );

// =======================================================
var idsetd = charIDToTypeID( "setd" );
    var desc40 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref12 = new ActionReference();
        var idcontentLayer = stringIDToTypeID( "contentLayer" );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref12.putEnumerated( idcontentLayer, idOrdn, idTrgt );
    desc40.putReference( idnull, ref12 );
    var idT = charIDToTypeID( "T   " );
        var desc41 = new ActionDescriptor();
        var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
            var desc42 = new ActionDescriptor();
            var idstrokeStyleLineWidth = stringIDToTypeID( "strokeStyleLineWidth" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc42.putUnitDouble( idstrokeStyleLineWidth, idPnt, 2.000000 );
            var idstrokeStyleVersion = stringIDToTypeID( "strokeStyleVersion" );
            desc42.putInteger( idstrokeStyleVersion, 2 );
            var idstrokeEnabled = stringIDToTypeID( "strokeEnabled" );
            desc42.putBoolean( idstrokeEnabled, true );
        var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
        desc41.putObject( idstrokeStyle, idstrokeStyle, desc42 );
    var idshapeStyle = stringIDToTypeID( "shapeStyle" );
    desc40.putObject( idT, idshapeStyle, desc41 );
executeAction( idsetd, desc40, DialogModes.NO );

// =======================================================
var idsetd = charIDToTypeID( "setd" );
    var desc43 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref13 = new ActionReference();
        var idcontentLayer = stringIDToTypeID( "contentLayer" );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref13.putEnumerated( idcontentLayer, idOrdn, idTrgt );
    desc43.putReference( idnull, ref13 );
    var idT = charIDToTypeID( "T   " );
        var desc44 = new ActionDescriptor();
        var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
            var desc45 = new ActionDescriptor();
            var idstrokeStyleLineWidth = stringIDToTypeID( "strokeStyleLineWidth" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc45.putUnitDouble( idstrokeStyleLineWidth, idPnt, 1.000000 );
            var idstrokeStyleVersion = stringIDToTypeID( "strokeStyleVersion" );
            desc45.putInteger( idstrokeStyleVersion, 2 );
            var idstrokeEnabled = stringIDToTypeID( "strokeEnabled" );
            desc45.putBoolean( idstrokeEnabled, true );
        var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
        desc44.putObject( idstrokeStyle, idstrokeStyle, desc45 );
    var idshapeStyle = stringIDToTypeID( "shapeStyle" );
    desc43.putObject( idT, idshapeStyle, desc44 );
executeAction( idsetd, desc43, DialogModes.NO );

// =======================================================
var idmove = charIDToTypeID( "move" );
    var desc46 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref14 = new ActionReference();
        var idLyr = charIDToTypeID( "Lyr " );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref14.putEnumerated( idLyr, idOrdn, idTrgt );
    desc46.putReference( idnull, ref14 );
    var idT = charIDToTypeID( "T   " );
        var ref15 = new ActionReference();
        var idLyr = charIDToTypeID( "Lyr " );
        ref15.putIndex( idLyr, 0 );
    desc46.putReference( idT, ref15 );
    var idAdjs = charIDToTypeID( "Adjs" );
    desc46.putBoolean( idAdjs, false );
    var idVrsn = charIDToTypeID( "Vrsn" );
    desc46.putInteger( idVrsn, 5 );
executeAction( idmove, desc46, DialogModes.NO );

// =======================================================
var idslct = charIDToTypeID( "slct" );
    var desc47 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref16 = new ActionReference();
        var idmarqueeRectTool = stringIDToTypeID( "marqueeRectTool" );
        ref16.putClass( idmarqueeRectTool );
    desc47.putReference( idnull, ref16 );
    var iddontRecord = stringIDToTypeID( "dontRecord" );
    desc47.putBoolean( iddontRecord, true );
    var idforceNotify = stringIDToTypeID( "forceNotify" );
    desc47.putBoolean( idforceNotify, true );
executeAction( idslct, desc47, DialogModes.NO );

// =======================================================
var idsetd = charIDToTypeID( "setd" );
    var desc48 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref17 = new ActionReference();
        var idChnl = charIDToTypeID( "Chnl" );
        var idfsel = charIDToTypeID( "fsel" );
        ref17.putProperty( idChnl, idfsel );
    desc48.putReference( idnull, ref17 );
    var idT = charIDToTypeID( "T   " );
        var desc49 = new ActionDescriptor();
        var idTop = charIDToTypeID( "Top " );
        var idRlt = charIDToTypeID( "#Rlt" );
        desc49.putUnitDouble( idTop, idRlt, 115.680000 );
        var idLeft = charIDToTypeID( "Left" );
        var idRlt = charIDToTypeID( "#Rlt" );
        desc49.putUnitDouble( idLeft, idRlt, 259.560000 );
        var idBtom = charIDToTypeID( "Btom" );
        var idRlt = charIDToTypeID( "#Rlt" );
        desc49.putUnitDouble( idBtom, idRlt, 367.560000 );
        var idRght = charIDToTypeID( "Rght" );
        var idRlt = charIDToTypeID( "#Rlt" );
        desc49.putUnitDouble( idRght, idRlt, 387.360000 );
    var idRctn = charIDToTypeID( "Rctn" );
    desc48.putObject( idT, idRctn, desc49 );
executeAction( idsetd, desc48, DialogModes.NO );

// =======================================================
var idslct = charIDToTypeID( "slct" );
    var desc50 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref18 = new ActionReference();
        var idLyr = charIDToTypeID( "Lyr " );
        ref18.putName( idLyr, "图层 1" );
    desc50.putReference( idnull, ref18 );
    var idMkVs = charIDToTypeID( "MkVs" );
    desc50.putBoolean( idMkVs, false );
executeAction( idslct, desc50, DialogModes.NO );

// =======================================================
var idInvs = charIDToTypeID( "Invs" );
executeAction( idInvs, undefined, DialogModes.NO );

// =======================================================
var idDlt = charIDToTypeID( "Dlt " );
executeAction( idDlt, undefined, DialogModes.NO );

// =======================================================
var idslct = charIDToTypeID( "slct" );
    var desc51 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref19 = new ActionReference();
        var idrectangleTool = stringIDToTypeID( "rectangleTool" );
        ref19.putClass( idrectangleTool );
    desc51.putReference( idnull, ref19 );
    var iddontRecord = stringIDToTypeID( "dontRecord" );
    desc51.putBoolean( iddontRecord, true );
    var idforceNotify = stringIDToTypeID( "forceNotify" );
    desc51.putBoolean( idforceNotify, true );
executeAction( idslct, desc51, DialogModes.NO );

// =======================================================
var idslct = charIDToTypeID( "slct" );
    var desc52 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref20 = new ActionReference();
        var idLyr = charIDToTypeID( "Lyr " );
        ref20.putName( idLyr, "矩形 1" );
    desc52.putReference( idnull, ref20 );
    var idMkVs = charIDToTypeID( "MkVs" );
    desc52.putBoolean( idMkVs, false );
executeAction( idslct, desc52, DialogModes.NO );

// =======================================================
var idslct = charIDToTypeID( "slct" );
    var desc53 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref21 = new ActionReference();
        var idmoveTool = stringIDToTypeID( "moveTool" );
        ref21.putClass( idmoveTool );
    desc53.putReference( idnull, ref21 );
    var iddontRecord = stringIDToTypeID( "dontRecord" );
    desc53.putBoolean( iddontRecord, true );
    var idforceNotify = stringIDToTypeID( "forceNotify" );
    desc53.putBoolean( idforceNotify, true );
executeAction( idslct, desc53, DialogModes.NO );

// =======================================================
var idTrnf = charIDToTypeID( "Trnf" );
    var desc54 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref22 = new ActionReference();
        var idPath = charIDToTypeID( "Path" );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref22.putEnumerated( idPath, idOrdn, idTrgt );
    desc54.putReference( idnull, ref22 );
    var idFTcs = charIDToTypeID( "FTcs" );
    var idQCSt = charIDToTypeID( "QCSt" );
    var idQcsa = charIDToTypeID( "Qcsa" );
    desc54.putEnumerated( idFTcs, idQCSt, idQcsa );
    var idOfst = charIDToTypeID( "Ofst" );
        var desc55 = new ActionDescriptor();
        var idHrzn = charIDToTypeID( "Hrzn" );
        var idRlt = charIDToTypeID( "#Rlt" );
        desc55.putUnitDouble( idHrzn, idRlt, -0.120000 );
        var idVrtc = charIDToTypeID( "Vrtc" );
        var idRlt = charIDToTypeID( "#Rlt" );
        desc55.putUnitDouble( idVrtc, idRlt, -0.000000 );
    var idOfst = charIDToTypeID( "Ofst" );
    desc54.putObject( idOfst, idOfst, desc55 );
    var idWdth = charIDToTypeID( "Wdth" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc54.putUnitDouble( idWdth, idPrc, 101.724138 );
executeAction( idTrnf, desc54, DialogModes.NO );

// =======================================================
var idtrim = stringIDToTypeID( "trim" );
    var desc56 = new ActionDescriptor();
    var idtrimBasedOn = stringIDToTypeID( "trimBasedOn" );
    var idtrimBasedOn = stringIDToTypeID( "trimBasedOn" );
    var idTrns = charIDToTypeID( "Trns" );
    desc56.putEnumerated( idtrimBasedOn, idtrimBasedOn, idTrns );
    var idTop = charIDToTypeID( "Top " );
    desc56.putBoolean( idTop, true );
    var idBtom = charIDToTypeID( "Btom" );
    desc56.putBoolean( idBtom, true );
    var idLeft = charIDToTypeID( "Left" );
    desc56.putBoolean( idLeft, true );
    var idRght = charIDToTypeID( "Rght" );
    desc56.putBoolean( idRght, true );
executeAction( idtrim, desc56, DialogModes.NO );

// =======================================================
var idsave = charIDToTypeID( "save" );
    var desc59 = new ActionDescriptor();
    var idAs = charIDToTypeID( "As  " );
        var desc60 = new ActionDescriptor();
        var idEQlt = charIDToTypeID( "EQlt" );
        desc60.putInteger( idEQlt, 12 );
        var idOptm = charIDToTypeID( "Optm" );
        desc60.putBoolean( idOptm, true );
        var idMttC = charIDToTypeID( "MttC" );
        var idMttC = charIDToTypeID( "MttC" );
        var idNone = charIDToTypeID( "None" );
        desc60.putEnumerated( idMttC, idMttC, idNone );
    var idJPEG = charIDToTypeID( "JPEG" );
    desc59.putObject( idAs, idJPEG, desc60 );
    var idIn = charIDToTypeID( "In  " );
    desc59.putPath( idIn, new File( fpath.toString()+a.toString()+"Pik.jpg" ) );
    var idDocI = charIDToTypeID( "DocI" );
    desc59.putInteger( idDocI, 39 );
    var idCpy = charIDToTypeID( "Cpy " );
    desc59.putBoolean( idCpy, true );
    var idsaveStage = stringIDToTypeID( "saveStage" );
    var idsaveStageType = stringIDToTypeID( "saveStageType" );
    var idsaveSucceeded = stringIDToTypeID( "saveSucceeded" );
    desc59.putEnumerated( idsaveStage, idsaveStageType, idsaveSucceeded );
executeAction( idsave, desc59, DialogModes.NO );

// =======================================================
var idCls = charIDToTypeID( "Cls " );
    var desc61 = new ActionDescriptor();
    var idSvng = charIDToTypeID( "Svng" );
    var idYsN = charIDToTypeID( "YsN " );
    var idN = charIDToTypeID( "N   " );
    desc61.putEnumerated( idSvng, idYsN, idN );
executeAction( idCls, desc61, DialogModes.NO );
}
for ( var i=1; i<=200; i++)
{
    try{
        Able(i,"D:\\xsj\\dj\\piks\\Pik_allin_cov5\\");
    }
    catch(err) {
    }
}

